### ISSUE TITLE
the red and dark matter tools don't work

### ISSUE THREAD

**Issue by judahking123** [Pitan76/item-alchemy#104]
charging  @and uncharging them does not work

**Comment by anthonymendez** [comment]
Looking into this, I'll see if I can figure out the cause :)

**Comment by anthonymendez** [comment]
One thing I noticed is that between 1.18.2 and 1.21, 1.21 doesn't show tool stats.

![1.18.2 Example](https://github.com/user-attachments/assets/b86ab3e7-ddf7-44b6-8c5f-219b50e7b0a1)
![1.21 Example](https://github.com/user-attachments/assets/86601094-f266-4548-a058-2da7c3d67fe4)

**Comment by anthonymendez** [comment]
Forgot to update this thread. I started work on my own mod to try and learn about Fabric & NeoForge dev and realized that this may be caused by 1.21 requiring the method [`getBonusDamage`](https://github.com/anthonymendez/Toeknee-s-Simple-Tools/commit/7a0686f19f2989612b9f4323c1347c918cc621f6#diff-4cf9d45902c0b1a3a044a3ddb9e2f2ef1212a6883f497aefba3ef4eb9c6381cdR53-R57) to be overridden. I'll try and work on a PR soon.

**Comment by KevinParnell** [comment]
When right clicking with a fully charged black matter pickaxe my game crashes with this error:When right clicking with a fully charged black matter pickaxe my game crashes with this error:
[17:35:22] [Render thread/WARN]: Suppressing EXPERIMENTAL level lifecycle[17:35:22] [Render thread/ERROR]: Unreported exception thrown!java.lang.NullPointerException: Cannot invoke "net.pitan76.mcpitanlib.api.util.CompatActionResult.toActionResult()" because the return value of "net.pitan76.mcpitanlib.api.item.ExtendItemProvider.onRightClickOnBlock(net.pitan76.mcpitanlib.api.event.item.ItemUseOnBlockEvent, net.pitan76.mcpitanlib.api.item.ExtendItemProvider$Options)" is null at net.minecraft.class_1792.handler$hcp002$mcpitanlib$useOnBlock(class_1792.java:9574) ~[client-intermediary.jar:?] at net.minecraft.class_1792.method_7884(class_1792.java) ~[client-intermediary.jar:?] at net.minecraft.class_1799.method_7981(class_1799.java:264) ~[client-intermediary.jar:?] at net.minecraft.class_636.method_41934(class_636.java:366) ~[client-intermediary.jar:?] at net.minecraft.class_636.method_41933(class_636.java:328) ~[client-intermediary.jar:?] at net.minecraft.class_636.method_41931(class_636.java:278) ~[client-intermediary.jar:?] at net.minecraft.class_636.method_2896(class_636.java:327) ~[client-intermediary.jar:?] at net.minecraft.class_310.method_1583(class_310.java:1748) ~[client-intermediary.jar:?] at net.minecraft.class_310.method_1508(class_310.java:2002) ~[client-intermediary.jar:?] at net.minecraft.class_310.method_1574(class_310.java:1829) ~[client-intermediary.jar:?] at net.minecraft.class_310.method_1523(class_310.java:1135) ~[client-intermediary.jar:?] at net.minecraft.class_310.method_1514(class_310.java:768) [client-intermediary.jar:?] at net.minecraft.client.main.Main.method_44604(Main.java:244) [client-intermediary.jar:?] at net.minecraft.client.main.Main.main(Main.java:51) [client-intermediary.jar:?] at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.15.11.jar:?] at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.11.jar:?] at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.15.11.jar:?] at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?] at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243) [NewLaunch.jar:?] at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278) [NewLaunch.jar:?] at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?] at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?][17:35:22] [Server thread/INFO]: Stopping server[17:35:22] [Server thread/INFO]: Saving players[17:35:22] [Server thread/INFO]: Saving worlds

I am on version 1.19.2
