### ISSUE TITLE
Kicked for "Inavalid player data" from Fabric 1.21 Server

### ISSUE THREAD

**Issue by Bufficorn** [Pitan76/item-alchemy#105]
With Item Alchemy installed I'm being kicked from the server with an "Inavalid player data" message. 

Removing only Item Alchemy and nothing else solves the issue completely.

Duplicate this event:
Fabric 0.16.0 server jar for MC 1.21 
mod version 0.9.0
MCPitan versions tried (occurring with both versions currently):
MCPitanLib version: 2.3.1 (as suggested in changelog for IA 0.9.0)
MCPitanLib version: 2.3.3 (auto-updated using Curseforge Launcher)

<details><summary>Disconnect Message</summary>
<p>

![image](https://github.com/user-attachments/assets/a8ff06ed-4caa-4e63-a01c-dd8f9d589232)

</p>
</details> 
<details><summary>Console</summary>
<p>

Relevant section of console during crash:

17.07 22:26:55 [Multicraft] The_Bufficorn ran command Message of the Day
17.07 22:26:55 [Server] Server thread/INFO Loading config from file...
17.07 22:26:55 [Server] Server thread/INFO The_Bufficorn joined the game
17.07 22:26:55 [Server] Server thread/ERROR Couldn't place player in world
17.07 22:26:55 [Server] INFO java.lang.NullPointerException: Cannot invoke "net.minecraft.class_8710$class_9154.comp_2242()" because "type" is null
17.07 22:26:55 [Server] INFO at dev.architectury.impl.NetworkAggregator.collectPackets(NetworkAggregator.java:143) ~[architectury-13.0.4-fabric.jar:?]
17.07 22:26:55 [Server] INFO at dev.architectury.networking.NetworkManager.collectPackets(NetworkManager.java:137) ~[architectury-13.0.4-fabric.jar:?]
17.07 22:26:55 [Server] INFO at dev.architectury.networking.NetworkManager.sendToPlayer(NetworkManager.java:157) ~[architectury-13.0.4-fabric.jar:?]
17.07 22:26:55 [Server] INFO at net.pitan76.mcpitanlib.api.network.ServerNetworking.send(ServerNetworking.java:21) ~[mcpitanlib-2.3.1-1.21-fabric.jar:?]
17.07 22:26:55 [Server] INFO at net.pitan76.itemalchemy.EMCManager.syncS2C_emc_map(EMCManager.java:307) ~[itemalchemy-0.9.0.jar:?]
17.07 22:26:55 [Server] INFO at net.pitan76.itemalchemy.ItemAlchemy.lambda$init$0(ItemAlchemy.java:62) ~[itemalchemy-0.9.0.jar:?]
17.07 22:26:55 [Server] INFO at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733) ~[?:?]
17.07 22:26:55 [Server] INFO at dev.architectury.event.EventFactory.invokeMethod(EventFactory.java:53) ~[architectury-13.0.4-fabric.jar:?]
17.07 22:26:55 [Server] INFO at dev.architectury.event.EventFactory$1.handleInvocation(EventFactory.java:62) ~[architectury-13.0.4-fabric.jar:?]
17.07 22:26:55 [Server] INFO at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:87) ~[guava-32.1.2-jre.jar:?]
17.07 22:26:55 [Server] INFO at jdk.proxy2/jdk.proxy2.$Proxy163.join(Unknown Source) ~[?:?]
17.07 22:26:55 [Server] INFO at net.minecraft.class_3324.handler$zcb000$architectury$placeNewPlayer(class_3324.java:1509) ~[server-intermediary.jar:?]
17.07 22:26:55 [Server] INFO at net.minecraft.class_3324.method_14570(class_3324.java:288) ~[server-intermediary.jar:?]
17.07 22:26:55 [Server] INFO at net.minecraft.class_8610.mixinextras$bridge$method_14570$36(class_8610.java) ~[server-intermediary.jar:?]
17.07 22:26:55 [Server] INFO at net.minecraft.class_8610.wrapOperation$cjj000$polymer-networking$polymerNet$prePlayHandshakeHackfest(class_8610.java:1038) ~[server-intermediary.jar:?]
17.07 22:26:55 [Server] INFO at net.minecraft.class_8610.method_52408(class_8610.java:152) ~[server-intermediary.jar:?]
17.07 22:26:55 [Server] INFO at net.minecraft.class_8736.method_53043(class_8736.java:22) ~[server-intermediary.jar:?]
17.07 22:26:55 [Server] INFO at net.minecraft.class_8736.method_11054(class_8736.java:8) ~[server-intermediary.jar:?]
17.07 22:26:55 [Server] INFO at net.minecraft.class_2600.method_11072(class_2600.java:27) ~[server-intermediary.jar:?]
17.07 22:26:55 [Server] INFO at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
17.07 22:26:55 [Server] INFO at net.minecraft.class_1255.method_18859(class_1255.java:162) ~[server-intermediary.jar:?]
17.07 22:26:55 [Server] INFO at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
17.07 22:26:55 [Server] INFO at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:864) ~[server-intermediary.jar:?]
17.07 22:26:55 [Server] INFO at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:173) ~[server-intermediary.jar:?]
17.07 22:26:55 [Server] INFO at net.minecraft.class_1255.method_16075(class_1255.java:136) ~[server-intermediary.jar:?]
17.07 22:26:55 [Server] INFO at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:846) ~[server-intermediary.jar:?]
17.07 22:26:55 [Server] INFO at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:840) ~[server-intermediary.jar:?]
17.07 22:26:55 [Server] INFO at net.minecraft.class_1255.method_18857(class_1255.java:145) ~[server-intermediary.jar:?]
17.07 22:26:55 [Server] INFO at net.minecraft.server.MinecraftServer.method_18857(MinecraftServer.java:810) ~[server-intermediary.jar:?]
17.07 22:26:55 [Server] INFO at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:815) ~[server-intermediary.jar:?]
17.07 22:26:55 [Server] INFO at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:702) ~[server-intermediary.jar:?]
17.07 22:26:55 [Server] INFO at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281) ~[server-intermediary.jar:?]
17.07 22:26:55 [Server] INFO at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
17.07 22:26:55 [Disconnect] User The_Bufficorn has disconnected, reason: Invalid player data
17.07 22:26:55 [Server] Server thread/INFO The_Bufficorn left the game

</p>
</details>

**Comment by PiusV** [comment]
Same

**Comment by flyover0112** [comment]
Same here Fabric 1.21 Server (tried home server and Nitrado server) cannot join world because "Invalid Player Data"


[03:51:37] [Server thread/INFO]: Fly0ver joined the game
[03:51:37] [Server thread/ERROR]: Couldn't place player in world
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_9139.encode(Object, Object)" because "codec" is null
	at dev.architectury.impl.NetworkAggregator.collectPackets(NetworkAggregator.java:146) ~[architectury-13.0.6-fabric.jar:?]
	at dev.architectury.networking.NetworkManager.collectPackets(NetworkManager.java:137) ~[architectury-13.0.6-fabric.jar:?]
	at dev.architectury.networking.NetworkManager.sendToPlayer(NetworkManager.java:157) ~[architectury-13.0.6-fabric.jar:?]
	at net.pitan76.mcpitanlib.api.network.ServerNetworking.send(ServerNetworking.java:23) ~[mcpitanlib-2.3.3-1.21-fabric.jar:?]
	at net.pitan76.itemalchemy.EMCManager.syncS2C_emc_map(EMCManager.java:307) ~[itemalchemy-0.9.0.jar:?]
	at net.pitan76.itemalchemy.ItemAlchemy.lambda$init$0(ItemAlchemy.java:62) ~[itemalchemy-0.9.0.jar:?]
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733) ~[?:?]
	at dev.architectury.event.EventFactory.invokeMethod(EventFactory.java:53) ~[architectury-13.0.6-fabric.jar:?]
	at dev.architectury.event.EventFactory$1.handleInvocation(EventFactory.java:62) ~[architectury-13.0.6-fabric.jar:?]
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:87) ~[guava-32.1.2-jre.jar:?]
	at jdk.proxy2/jdk.proxy2.$Proxy182.join(Unknown Source) ~[?:?]
	at net.minecraft.class_3324.handler$zcc000$architectury$placeNewPlayer(class_3324.java:2009) ~[server-intermediary.jar:?]
	at net.minecraft.class_3324.method_14570(class_3324.java:288) ~[server-intermediary.jar:?]
	at net.minecraft.class_8610.mixinextras$bridge$method_14570$45(class_8610.java) ~[server-intermediary.jar:?]
	at net.minecraft.class_8610.wrapOperation$ddj000$polymer-networking$polymerNet$prePlayHandshakeHackfest(class_8610.java:1038) ~[server-intermediary.jar:?]
	at net.minecraft.class_8610.method_52408(class_8610.java:152) ~[server-intermediary.jar:?]
	at net.minecraft.class_8736.method_53043(class_8736.java:22) ~[server-intermediary.jar:?]
	at net.minecraft.class_8736.method_11054(class_8736.java:8) ~[server-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:27) ~[server-intermediary.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:162) ~[server-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:864) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:173) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:136) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:846) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:840) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:121) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:814) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:702) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281) ~[server-intermediary.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
[03:51:38] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 2137ms or 42 ticks behind
[03:51:38] [Server thread/INFO]: Fly0ver lost connection: Invalid player data
[03:51:38] [Server thread/INFO]: Fly0ver left the game

**Comment by JakeYde** [comment]
Same issue here as well.

**Comment by PTOM76** [comment]
Fixed
