### ISSUE TITLE
Still not working properly on Fabric Server for 1.21.1

### ISSUE THREAD

**Issue by JakeYde** [Pitan76/item-alchemy#120]
Seems like mcpitanlib-2.3.9-1.21-fabric broke compatibility again.
![image](https://github.com/user-attachments/assets/eea77cc6-5470-4dea-86e3-1bdfd2a62cb0)
https://pastebin.com/qpNtPEZ5

**Comment by flyover0112** [comment]
Same here, Fabric 1.21 server with latest fabric version.

[08:35:00] [Server thread/ERROR]: Couldn't place player in world
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_9139.encode(Object, Object)" because "codec" is null
	at dev.architectury.impl.NetworkAggregator.collectPackets(NetworkAggregator.java:146) ~[architectury-13.0.6-fabric.jar:?]
	at dev.architectury.networking.NetworkManager.collectPackets(NetworkManager.java:137) ~[architectury-13.0.6-fabric.jar:?]
	at dev.architectury.networking.NetworkManager.sendToPlayer(NetworkManager.java:157) ~[architectury-13.0.6-fabric.jar:?]
	at net.pitan76.mcpitanlib.api.network.ServerNetworking.send(ServerNetworking.java:31) ~[mcpitanlib-2.4.0-1.21-fabric.jar:?]
	at net.pitan76.itemalchemy.EMCManager.syncS2C_emc_map(EMCManager.java:307) ~[itemalchemy-0.9.1.jar:?]
	at net.pitan76.itemalchemy.ItemAlchemy.lambda$init$0(ItemAlchemy.java:56) ~[itemalchemy-0.9.1.jar:?]
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733) ~[?:?]
	at dev.architectury.event.EventFactory.invokeMethod(EventFactory.java:53) ~[architectury-13.0.6-fabric.jar:?]
	at dev.architectury.event.EventFactory$1.handleInvocation(EventFactory.java:62) ~[architectury-13.0.6-fabric.jar:?]
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:87) ~[guava-32.1.2-jre.jar:?]
	at jdk.proxy2/jdk.proxy2.$Proxy203.join(Unknown Source) ~[?:?]
	at net.minecraft.class_3324.handler$zgf000$architectury$placeNewPlayer(class_3324.java:2009) ~[server-intermediary.jar:?]
	at net.minecraft.class_3324.method_14570(class_3324.java:288) ~[server-intermediary.jar:?]
	at net.minecraft.class_8610.mixinextras$bridge$method_14570$45(class_8610.java) ~[server-intermediary.jar:?]
	at net.minecraft.class_8610.wrapOperation$dhk000$polymer-networking$polymerNet$prePlayHandshakeHackfest(class_8610.java:1038) ~[server-intermediary.jar:?]
	at net.minecraft.class_8610.method_52408(class_8610.java:152) ~[server-intermediary.jar:?]
	at net.minecraft.class_8736.method_53043(class_8736.java:22) ~[server-intermediary.jar:?]
	at net.minecraft.class_8736.method_11054(class_8736.java:8) ~[server-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:27) ~[server-intermediary.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:162) ~[server-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:864) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:173) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:136) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:846) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:840) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:145) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18857(MinecraftServer.java:810) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:815) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:702) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281) ~[server-intermediary.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
[08:35:01] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 2308ms or 46 ticks behind
[08:35:01] [Server thread/INFO]: Fly0ver lost connection: Invalid player data
[08:35:01] [Server thread/INFO]: Fly0ver left the game
[08:35:01] [Server thread/INFO]: Receiving client config
[08:37:29] [User Authenticator #3/INFO]: UUID of player Fly0ver is 10db90db-6300-4edb-bc27-7acf962484f8
save-all
[08:37:30] [Server thread/INFO]: Saving the game (this may take a moment!)
[08:37:30] [Server thread/INFO]: Saved the game
[08:37:30] [Server thread/INFO]: Fly0ver[/202.168.76.65:51340] logged in with entity id 9 at (-6.5, 102.0, -8.5)
[08:37:30] [Server thread/INFO]: Sending server config values to client
[08:37:30] [Server thread/INFO]: Reading config values from file.
[08:37:30] [Server thread/INFO]: Loading config from file...
[08:37:30] [Server thread/INFO]: Fly0ver joined the game
[08:37:30] [Server thread/ERROR]: Couldn't place player in world
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_9139.encode(Object, Object)" because "codec" is null
	at dev.architectury.impl.NetworkAggregator.collectPackets(NetworkAggregator.java:146) ~[architectury-13.0.6-fabric.jar:?]
	at dev.architectury.networking.NetworkManager.collectPackets(NetworkManager.java:137) ~[architectury-13.0.6-fabric.jar:?]
	at dev.architectury.networking.NetworkManager.sendToPlayer(NetworkManager.java:157) ~[architectury-13.0.6-fabric.jar:?]
	at net.pitan76.mcpitanlib.api.network.ServerNetworking.send(ServerNetworking.java:31) ~[mcpitanlib-2.4.0-1.21-fabric.jar:?]
	at net.pitan76.itemalchemy.EMCManager.syncS2C_emc_map(EMCManager.java:307) ~[itemalchemy-0.9.1.jar:?]
	at net.pitan76.itemalchemy.ItemAlchemy.lambda$init$0(ItemAlchemy.java:56) ~[itemalchemy-0.9.1.jar:?]
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733) ~[?:?]
	at dev.architectury.event.EventFactory.invokeMethod(EventFactory.java:53) ~[architectury-13.0.6-fabric.jar:?]
	at dev.architectury.event.EventFactory$1.handleInvocation(EventFactory.java:62) ~[architectury-13.0.6-fabric.jar:?]
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:87) ~[guava-32.1.2-jre.jar:?]
	at jdk.proxy2/jdk.proxy2.$Proxy203.join(Unknown Source) ~[?:?]
	at net.minecraft.class_3324.handler$zgf000$architectury$placeNewPlayer(class_3324.java:2009) ~[server-intermediary.jar:?]
	at net.minecraft.class_3324.method_14570(class_3324.java:288) ~[server-intermediary.jar:?]
	at net.minecraft.class_8610.mixinextras$bridge$method_14570$45(class_8610.java) ~[server-intermediary.jar:?]
	at net.minecraft.class_8610.wrapOperation$dhk000$polymer-networking$polymerNet$prePlayHandshakeHackfest(class_8610.java:1038) ~[server-intermediary.jar:?]
	at net.minecraft.class_8610.method_52408(class_8610.java:152) ~[server-intermediary.jar:?]
	at net.minecraft.class_8736.method_53043(class_8736.java:22) ~[server-intermediary.jar:?]
	at net.minecraft.class_8736.method_11054(class_8736.java:8) ~[server-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:27) ~[server-intermediary.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:162) ~[server-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:864) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:173) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:136) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:846) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:840) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:145) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18857(MinecraftServer.java:810) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:815) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:702) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281) ~[server-intermediary.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
[08:37:30] [Server thread/INFO]: Fly0ver lost connection: Invalid player data
[08:37:30] [Server thread/INFO]: Fly0ver left the game

**Comment by PTOM76** [comment]
uploaded the latest MCPitanLib.

**Comment by flyover0112** [comment]
Now working fine on the 1.21 server, however, can we have an item that will link EMC storage with our external storage like Tom's Storage? An example will be mod "EMC Link" which is for ProjectE on forge.

**Comment by JakeYde** [comment]
Mod is loading fine, but it refuses to remember a player's learned recipes and stored EMC values.

> uploaded the latest MCPitanLib.

**Comment by PTOM76** [comment]
Fixed. thank you very much.
