### ISSUE TITLE
Can't respawn

### ISSUE THREAD

**Issue by bmfyMaple** [Pitan76/item-alchemy#42]
After dying, clicking the "Respawn" button does nothing, the following is the output report.
I'm not sure if this bug is caused by this mod, but I can respawn normally after removing this mod
[22:12:30] [Render thread/WARN]: Unable to play empty soundEvent: minecraft:entity.snow_golem.ambient
[22:13:19] [Server thread/INFO]: bmfy_bot掉出了这个世界
[22:13:19] [Server thread/INFO]: [bmfy_bot: 杀死了bmfy_bot]
[22:13:19] [Render thread/INFO]: Mixing client.MixinGuiMessageTag from nochatreports.mixins.json into net.minecraft.class_7591
[22:13:19] [Render thread/INFO]: [CHAT] bmfy_bot掉出了这个世界
[22:13:19] [Render thread/INFO]: [CHAT] 杀死了bmfy_bot
[22:13:22] [Server thread/ERROR]: Failed to handle packet net.minecraft.class_2799@21d97fcb, suppressing error
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2520.method_23258()" because "$$0" is null
	at net.minecraft.class_2512.method_25930(class_2512.java:190) ~[client-intermediary.jar:?]
	at net.minecraft.class_2487.method_25926(class_2487.java:214) ~[client-intermediary.jar:?]
	at net.minecraft.class_1657.handler$eop000$prefab$writeCustomDataToTag(class_1657.java:16861) ~[client-intermediary.jar:?]
	at net.minecraft.class_1657.method_5652(class_1657.java:898) ~[client-intermediary.jar:?]
	at net.minecraft.class_3222.method_5652(class_3222.java:345) ~[client-intermediary.jar:?]
	at net.minecraft.class_3222.handler$dog001$itemalchemy$copyFrom(class_3222.java:12265) ~[client-intermediary.jar:?]
	at net.minecraft.class_3222.method_14203(class_3222.java:1235) ~[client-intermediary.jar:?]
	at net.minecraft.class_3324.method_14556(class_3324.java:486) ~[client-intermediary.jar:?]
	at net.minecraft.class_3244.method_12068(class_3244.java:1720) ~[client-intermediary.jar:?]
	at net.minecraft.class_2799.method_12120(class_2799.java:24) ~[client-intermediary.jar:?]
	at net.minecraft.class_2799.method_11054(class_2799.java:6) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[client-intermediary.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:159) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:140) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:737) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$zop000$carpet$modifiedRunLoop(MinecraftServer.java:5394) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:644) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[22:13:24] [Server thread/ERROR]: Failed to handle packet net.minecraft.class_2799@4f330054, suppressing error
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2520.method_23258()" because "$$0" is null
	at net.minecraft.class_2512.method_25930(class_2512.java:190) ~[client-intermediary.jar:?]
	at net.minecraft.class_2487.method_25926(class_2487.java:214) ~[client-intermediary.jar:?]
	at net.minecraft.class_1657.handler$eop000$prefab$writeCustomDataToTag(class_1657.java:16861) ~[client-intermediary.jar:?]
	at net.minecraft.class_1657.method_5652(class_1657.java:898) ~[client-intermediary.jar:?]
	at net.minecraft.class_3222.method_5652(class_3222.java:345) ~[client-intermediary.jar:?]
	at net.minecraft.class_3222.handler$dog001$itemalchemy$copyFrom(class_3222.java:12265) ~[client-intermediary.jar:?]
	at net.minecraft.class_3222.method_14203(class_3222.java:1235) ~[client-intermediary.jar:?]
	at net.minecraft.class_3324.method_14556(class_3324.java:486) ~[client-intermediary.jar:?]
	at net.minecraft.class_3244.method_12068(class_3244.java:1720) ~[client-intermediary.jar:?]
	at net.minecraft.class_2799.method_12120(class_2799.java:24) ~[client-intermediary.jar:?]
	at net.minecraft.class_2799.method_11054(class_2799.java:6) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[client-intermediary.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:159) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:140) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:737) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$zop000$carpet$modifiedRunLoop(MinecraftServer.java:5394) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:644) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[22:13:26] [Server thread/ERROR]: Failed to handle packet net.minecraft.class_2799@21b25125, suppressing error
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2520.method_23258()" because "$$0" is null
	at net.minecraft.class_2512.method_25930(class_2512.java:190) ~[client-intermediary.jar:?]
	at net.minecraft.class_2487.method_25926(class_2487.java:214) ~[client-intermediary.jar:?]
	at net.minecraft.class_1657.handler$eop000$prefab$writeCustomDataToTag(class_1657.java:16861) ~[client-intermediary.jar:?]
	at net.minecraft.class_1657.method_5652(class_1657.java:898) ~[client-intermediary.jar:?]
	at net.minecraft.class_3222.method_5652(class_3222.java:345) ~[client-intermediary.jar:?]
	at net.minecraft.class_3222.handler$dog001$itemalchemy$copyFrom(class_3222.java:12265) ~[client-intermediary.jar:?]
	at net.minecraft.class_3222.method_14203(class_3222.java:1235) ~[client-intermediary.jar:?]
	at net.minecraft.class_3324.method_14556(class_3324.java:486) ~[client-intermediary.jar:?]
	at net.minecraft.class_3244.method_12068(class_3244.java:1720) ~[client-intermediary.jar:?]
	at net.minecraft.class_2799.method_12120(class_2799.java:24) ~[client-intermediary.jar:?]
	at net.minecraft.class_2799.method_11054(class_2799.java:6) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[client-intermediary.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:159) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:140) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:737) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$zop000$carpet$modifiedRunLoop(MinecraftServer.java:5394) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:644) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[22:13:27] [Server thread/ERROR]: Failed to handle packet net.minecraft.class_2799@3c15533c, suppressing error
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2520.method_23258()" because "$$0" is null
	at net.minecraft.class_2512.method_25930(class_2512.java:190) ~[client-intermediary.jar:?]
	at net.minecraft.class_2487.method_25926(class_2487.java:214) ~[client-intermediary.jar:?]
	at net.minecraft.class_1657.handler$eop000$prefab$writeCustomDataToTag(class_1657.java:16861) ~[client-intermediary.jar:?]
	at net.minecraft.class_1657.method_5652(class_1657.java:898) ~[client-intermediary.jar:?]
	at net.minecraft.class_3222.method_5652(class_3222.java:345) ~[client-intermediary.jar:?]
	at net.minecraft.class_3222.handler$dog001$itemalchemy$copyFrom(class_3222.java:12265) ~[client-intermediary.jar:?]
	at net.minecraft.class_3222.method_14203(class_3222.java:1235) ~[client-intermediary.jar:?]
	at net.minecraft.class_3324.method_14556(class_3324.java:486) ~[client-intermediary.jar:?]
	at net.minecraft.class_3244.method_12068(class_3244.java:1720) ~[client-intermediary.jar:?]
	at net.minecraft.class_2799.method_12120(class_2799.java:24) ~[client-intermediary.jar:?]
	at net.minecraft.class_2799.method_11054(class_2799.java:6) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[client-intermediary.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:159) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:140) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:737) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$zop000$carpet$modifiedRunLoop(MinecraftServer.java:5394) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:644) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[22:13:28] [Server thread/ERROR]: Failed to handle packet net.minecraft.class_2799@39e07c85, suppressing error
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2520.method_23258()" because "$$0" is null
	at net.minecraft.class_2512.method_25930(class_2512.java:190) ~[client-intermediary.jar:?]
	at net.minecraft.class_2487.method_25926(class_2487.java:214) ~[client-intermediary.jar:?]
	at net.minecraft.class_1657.handler$eop000$prefab$writeCustomDataToTag(class_1657.java:16861) ~[client-intermediary.jar:?]
	at net.minecraft.class_1657.method_5652(class_1657.java:898) ~[client-intermediary.jar:?]
	at net.minecraft.class_3222.method_5652(class_3222.java:345) ~[client-intermediary.jar:?]
	at net.minecraft.class_3222.handler$dog001$itemalchemy$copyFrom(class_3222.java:12265) ~[client-intermediary.jar:?]
	at net.minecraft.class_3222.method_14203(class_3222.java:1235) ~[client-intermediary.jar:?]
	at net.minecraft.class_3324.method_14556(class_3324.java:486) ~[client-intermediary.jar:?]
	at net.minecraft.class_3244.method_12068(class_3244.java:1720) ~[client-intermediary.jar:?]
	at net.minecraft.class_2799.method_12120(class_2799.java:24) ~[client-intermediary.jar:?]
	at net.minecraft.class_2799.method_11054(class_2799.java:6) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[client-intermediary.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:159) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:140) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:737) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$zop000$carpet$modifiedRunLoop(MinecraftServer.java:5394) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:644) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by bmfyMaple** [comment]
Sorry, I now know that it conflicts with the prefab mod

**Comment by PTOM76** [comment]
please, tell me game version

**Comment by bmfyMaple** [comment]
Thanks for your reply！Here is the relevant version：
minecraft:1.19.2
fabric:0.14.19
itemalchemy:0.5.6
mcpitanlibarch:1.6.3
prefab:4.24
cloth config api:8.2.88
I'm so sorry this is the first time I report game problems so I'm not very clear about what you actually need so I've listed all the relevant version numbers.Anyway, thanks for your work!

**Comment by RetroRider5** [comment]
Same
