### ISSUE TITLE
Can't Respawn!

### ISSUE THREAD

**Issue by RetroRider5** [Pitan76/item-alchemy#50]
[20:34:49] [Server thread/ERROR]: Failed to handle packet net.minecraft.class_2799@67e1c3cd, suppressing error
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2520.method_23258()" because "$$0" is null
	at net.minecraft.class_2512.method_25930(class_2512.java:190) ~[client-intermediary.jar:?]
	at net.minecraft.class_2487.method_25926(class_2487.java:214) ~[client-intermediary.jar:?]
	at net.minecraft.class_1657.handler$ffo000$prefab$writeCustomDataToTag(class_1657.java:27361) ~[client-intermediary.jar:?]
	at net.minecraft.class_1657.method_5652(class_1657.java:898) ~[client-intermediary.jar:?]
	at net.minecraft.class_3222.method_5652(class_3222.java:345) ~[client-intermediary.jar:?]
	at net.minecraft.class_3222.handler$dno000$itemalchemy$copyFrom(class_3222.java:12765) ~[client-intermediary.jar:?]
	at net.minecraft.class_3222.method_14203(class_3222.java:1235) ~[client-intermediary.jar:?]
	at net.minecraft.class_3324.method_14556(class_3324.java:486) ~[client-intermediary.jar:?]
	at net.minecraft.class_3244.method_12068(class_3244.java:1720) ~[client-intermediary.jar:?]
	at net.minecraft.class_2799.method_12120(class_2799.java:24) ~[client-intermediary.jar:?]
	at net.minecraft.class_2799.method_11054(class_2799.java:6) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[client-intermediary.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:159) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:140) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:737) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:669) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
	
	Please fix conflict with prefab mod. Thanks.

Minecraft Version : 1.19.2
Fabric Ver. 0.14.21 - 1.19.2

**Comment by MikeInChina** [comment]
Yes this mod is truely conflict with prefab. Try delate one of them.

**Comment by RetroRider5** [comment]
> Yes this mod is truely conflict with prefab. Try delate one of them.

Can't lol I need prefab and I need item-alchemy mod lol.

Please fix it if can...

**Comment by PTOM76** [comment]
uploaded v0.6.6

**Comment by PTOM76** [comment]
thank you
