### ISSUE TITLE
Crashing upon starting game

### ISSUE THREAD

**Issue by Vamoply** [Pitan76/item-alchemy#55]
Every time I try to initialize the game I get this error
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2023-06-28 16:27:31
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'itemalchemy'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:458)
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoSuchFieldError: ATTACK_ENTITY
	at ml.pkom.mcpitanlibarch.api.event.v0.AttackEntityEventRegistry.register(AttackEntityEventRegistry.java:15)
	at ml.pkom.itemalchemy.item.AlchemicalSword.<init>(AlchemicalSword.java:13)
	at ml.pkom.itemalchemy.item.Items.lambda$init$24(Items.java:84)
	at dev.architectury.registry.registries.fabric.RegistriesImpl$RegistrarImpl.register(RegistriesImpl.java:211)
	at ml.pkom.mcpitanlibarch.core.registry.MCPLRegistry.registryItem(MCPLRegistry.java:48)
	at ml.pkom.mcpitanlibarch.api.registry.ArchRegistry.registerItem(ArchRegistry.java:47)
	at ml.pkom.itemalchemy.item.Items.init(Items.java:84)
	at ml.pkom.itemalchemy.ItemAlchemy.init(ItemAlchemy.java:52)
	at ml.pkom.itemalchemy.FabricMain.onInitialize(FabricMain.java:13)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 8 more

**Comment by PTOM76** [comment]
what is game version?

**Comment by Vamoply** [comment]
1.19.1

**Comment by PTOM76** [comment]
i think that the cause what MCPitanLib some APIs are not compatible with 1.19.1.
