### ISSUE TITLE
[1.20.1] crashes on loading level

### ISSUE THREAD

**Issue by Seegras** [Pitan76/item-alchemy#60]
First time after adding the mod:
```
Time: 2023-07-05 16:56:18
Description: Exception in server tick loop

java.lang.NoSuchMethodError: 'net.minecraft.class_3218 net.minecraft.class_3222.method_14220()'
        at ml.pkom.itemalchemy.ItemAlchemy.lambda$init$1(ItemAlchemy.java:61)
        at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
        at dev.architectury.event.EventFactory.invokeMethod(EventFactory.java:53)
        at dev.architectury.event.EventFactory$1.handleInvocation(EventFactory.java:62)
        at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:87)
        at jdk.proxy2/jdk.proxy2.$Proxy217.join(Unknown Source)
        at net.minecraft.class_3324.handler$zec000$architectury$placeNewPlayer(class_3324.java:1020)
        at net.minecraft.class_3324.method_14570(class_3324.java:307)
        at net.minecraft.class_3248.method_33800(class_3248.java:131)
        at net.minecraft.class_3248.md1165b8$polymer-networking$lambda$polymerNet$prePlayHandshakeHackfest$0$0(class_3248.java:2549)
        at eu.pb4.polymer.networking.impl.EarlyConnectionMagic.lambda$handle$0(EarlyConnectionMagic.java:31)
        at eu.pb4.polymer.networking.api.EarlyPlayNetworkHandler.lambda$onKeepAlive$0(EarlyPlayNetworkHandler.java:107)
        at net.minecraft.class_3738.run(class_3738.java:18)
        at net.minecraft.class_1255.method_18859(class_1255.java:156)
        at net.minecraft.class_4093.method_18859(class_4093.java:23)
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782)
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164)
        at net.minecraft.class_1255.method_16075(class_1255.java:130)
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:8318)
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758)
        at net.minecraft.class_1255.method_5383(class_1255.java:115)
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:742)
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675)
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
        at java.base/java.lang.Thread.run(Thread.java:833)

```

**Comment by Seegras** [comment]
Works!
