### ISSUE TITLE
Crafting Alchemy Table Crashes Game

### ISSUE THREAD

**Issue by MLMII** [Pitan76/item-alchemy#78]
Oddly enough when I reload the world the Alchemy Table as well as the ingredients are laying on the ground in front of the crafting table.

---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 2023-11-10 03:03:45
Description: Container click

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1935.method_8389()" because "$$0" is null
	at net.minecraft.class_1799.<init>(class_1799.java:169)
	at net.minecraft.class_1799.<init>(class_1799.java:152)
	at net.minecraft.class_1860.method_8111(class_1860.java:28)
	at net.minecraft.class_1863.method_8128(class_1863.java:109)
	at net.minecraft.class_1734.method_7667(class_1734.java:59)
	at net.minecraft.class_1703.method_34249(class_1703.java:421)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at net.minecraft.class_1703.method_30010(class_1703.java:419)
	at net.minecraft.class_1703.method_7593(class_1703.java:294)
	at net.minecraft.class_636.method_2906(class_636.java:450)
	at net.minecraft.class_465.method_2383(class_465.java:548)
	at net.minecraft.class_479.method_2383(class_479.java:104)
	at net.minecraft.class_465.method_25402(class_465.java:340)
	at net.minecraft.class_479.method_25402(class_479.java:93)
	at net.minecraft.class_312.method_1611(class_312.java:98)
	at net.minecraft.class_437.method_25412(class_437.java:409)
	at net.minecraft.class_312.method_1601(class_312.java:98)
	at net.minecraft.class_312.method_22686(class_312.java:169)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:169)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:237)
	at net.minecraft.class_310.method_1523(class_310.java:1244)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:524)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:84)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)

**Comment by JakeYde** [comment]
Same issue
