### ISSUE TITLE
[1.20.2] Crash loading existing world after adding IA

### ISSUE THREAD

**Issue by BernardoGrigiastro** [Pitan76/item-alchemy#80]
Description: Exception in server tick loop

java.lang.ClassCastException: class net.minecraft.class_1867 cannot be cast to class net.minecraft.class_8786 (net.minecraft.class_1867 and net.minecraft.class_8786 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @5c3bd550)
	at ml.pkom.mcpitanlibarch.api.util.RecipeUtil.getAllRecipes(RecipeUtil.java:35)
	at ml.pkom.itemalchemy.EMCManager.setEmcFromRecipes(EMCManager.java:500)
	at ml.pkom.itemalchemy.EMCManager.init(EMCManager.java:142)
	at dev.architectury.event.fabric.EventHandlerImpl.lambda$registerCommon$9(EventHandlerImpl.java:65)
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$2(ServerLifecycleEvents.java:49)
	at net.minecraft.server.MinecraftServer.handler$bnm000$fabric-lifecycle-events-v1$afterSetupServer(MinecraftServer.java:5351)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:646)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:263)
	at java.base/java.lang.Thread.run(Thread.java:1583)

itemalchemy-0.7.6
mcpitanlibarch-1.8.3-1.20.2-fabric
Fabric Loader 0.14.24
Fabric API 0.90.7
lots of mods

**Comment by japherwocky** [comment]
I get this error as well, on a new world with nothing but fabric, architectury, cloth, sodium, iris, and REI.

using IA 0.7.6 and mcpitanlibarch-1.8.3-1.20.2-fabric

**Comment by PTOM76** [comment]
what is IA?
