### ISSUE TITLE
Fabric 1.20.2 | Mod Ver 0.7.6 | Crash with exit code -1073740791 when loading world.

### ISSUE THREAD

**Issue by LUNGSVVORLD** [Pitan76/item-alchemy#81]
It is described as an exception in server tick loop, following log is attached.
`java.lang.ClassCastException: class net.minecraft.class_1867 cannot be cast to class net.minecraft.class_8786 (net.minecraft.class_1867 and net.minecraft.class_8786 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @6e1ec318)
	at ml.pkom.mcpitanlibarch.api.util.RecipeUtil.getAllRecipes(RecipeUtil.java:35)
	at ml.pkom.itemalchemy.EMCManager.setEmcFromRecipes(EMCManager.java:500)
	at ml.pkom.itemalchemy.EMCManager.init(EMCManager.java:142)
	at dev.architectury.event.fabric.EventHandlerImpl.lambda$registerCommon$9(EventHandlerImpl.java:65)
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$2(ServerLifecycleEvents.java:49)
	at net.minecraft.server.MinecraftServer.handler$zha000$fabric-lifecycle-events-v1$afterSetupServer(MinecraftServer.java:2351)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:646)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:263)
	at java.base/java.lang.Thread.run(Thread.java:833)`

All dependencies are downloaded, crash does not occur when Item Alchemy is removed. The crash only happens once a world has finished loading and occurs during the "entering world" text after world loading has reached 100%. 
My current assumption is some sort of compatibility issue with REI although the log screams with multiple separate issues related to Item Alchemy whenever I load it which makes me think it's more likely just a really buggy build. The log shows parsing errors, missing textures, and more.

**Comment by japherwocky** [comment]
this is the same thing happening in #80 - removing REI did not fix it for me.
